# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20160414_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='eligibility',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='startup',
            name='procedure',
            field=models.TextField(default=None),
        ),
    ]
