# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20160414_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='eligibility',
            field=models.TextField(default='Eligibility Criteria'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='procedure',
            field=models.TextField(default='Procedure'),
        ),
    ]
