# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20160414_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='eligibility',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='procedure',
        ),
    ]
