# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 17:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20160414_2308'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Startup',
            new_name='Scholarship',
        ),
    ]
