# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20160414_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='eligibility',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='procedure',
        ),
    ]
