# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20160415_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='eligibility',
            field=models.TextField(default='Put the text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scholarship',
            name='procedure',
            field=models.TextField(default='Text'),
            preserve_default=False,
        ),
    ]
